import 'package:flutter/material.dart';
import 'package:flutter_mvvm_stacked/core/app/app.locator.dart';
import 'package:flutter_mvvm_stacked/core/app/app.router.dart';
import 'package:stacked_services/stacked_services.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await setupLocator(); // Generated by stacked_generator
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter MVVM Stacked',
      navigatorKey: StackedService.navigatorKey, // Important for Stacked Services
      onGenerateRoute: StackedRouter().onGenerateRoute, // Generated by stacked_generator
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      // We don't need a home property as initial route is handled by StackedRouter
    );
  }
}
